#!/bin/bash
# run-make-batch: make next batch file for annotator
# usage: run-make-batch id
# note: parameter id is a single digit
# 20170924 erikt(at)xs4all.nl

COMMAND=$0
ID=$1
if [ -z "$ID" ]; then echo "usage: run-make-batch id">&2; exit 1; fi
LASTID=$(($ID-1))

FASTTEXTDIR=/home/cloud/software/fastText/replyto
PYTHONDIR=/home/cloud/projects/online-behaviour/machine-learning
ANNOTATIONS=ANNOTATIONS.annotate

if [ $ID != "1" ]; then
   cd $PYTHONDIR
   if [ "`cat $ANNOTATIONS|wc -l`" != "220" ]; then
      echo "annotations problem">&2
      exit 1
   fi
   ebackup $ANNOTATIONS
   cut -d' ' -f1,3 ANNOTATIONS.annotate | sort -n |\
      paste -d' ' - active-0$LASTID | cut -d' ' -f2,5- | sed 's/^/__label__/' |\
      head -110 > $FASTTEXTDIR/ACTIVE-0$LASTID
   
   cd $FASTTEXTDIR
   tail -n +111 run-selected-a.0$LASTID | cut -d' ' -f2- > REST.unique.0$LASTID
fi
cd $FASTTEXTDIR
./run-select $ID

ebackup run-selected-a.0$ID
head -110 run-selected-a.0$ID | cut -d' ' -f2- > $PYTHONDIR/active-0$ID
NEXTID=$(($ID+0))
head -$NEXTID${NEXTID}0 TRAIN.random | tail -110 >> $PYTHONDIR/active-0$ID
cat TRAIN ACTIVE-?? > TRAIN+ACTIVE
wc TRAIN+ACTIVE
../fasttext supervised -input TRAIN+ACTIVE -output model -dim 300 \
   -minCount 5 -pretrainedVectors model-a.vec > /dev/null 2>/dev/null
../fasttext predict model.bin $PYTHONDIR/active-0$ID \
   > $PYTHONDIR/active-0$ID.labels

cd $PYTHONDIR
paste -d' ' active-0$ID.labels active-0$ID > active-0$ID.tmp
ebackup -r active-0$ID
mv active-0$ID.tmp active-0$ID
chmod 444 active-0$ID
rm -f active
ln -s active-0$ID active
if [ $ID != "1" ]; then
   chmod 444 $ANNOTATIONS
   mv $ANNOTATIONS $ANNOTATIONS.0$LASTID
   touch $ANNOTATIONS
   COUNT="`grep -v __None $ANNOTATIONS.0$LASTID | cut -d' ' -f2,3 | sed 's/__label__//' | grep '^\(.*\) \1$' | wc -l`"
   echo ${COUNT}000/110 | bc | sed 's/^/Human: /' | sed 's/\(.\) *$/.\1%/'
fi

cd $FASTTEXTDIR
./run-eval | tee run-eval.out.active.0$LASTID | $PYTHONDIR/average.py

exit 0
